### PR TITLE
Correct Docker invocation and dep updates

### PR DESCRIPTION
**Pull request by mjw99**

### CODE REVIEW

**Comment by johnmay** [comment]
Thanks will be a release soon updating to CDK 2.8, have it locally and testing

**Comment by mjw99** [comment]
I was also considering switching the image to use the JRE from eclipse-temurin:17-jre-alpine

**Comment by johnmay** [comment]
whats the size diff?

**Comment by mjw99** [comment]
I think around 80M bigger

**Comment by johnmay** [comment]
Will look into it

**Comment by johnmay** [comment]
80MB is more than double the size right?

**Comment by johnmay** [comment]
What's the advantage of termurin? Why not openjdk:17-alpine

**Comment by mjw99** [comment]
> +80MB is more than double the size right?

Yes:
```
$ docker images | grep jre
eclipse-temurin   17-jre-alpine      cabdba77eafb   3 weeks ago    168MB
openjdk           8u212-jre-alpine   f7a292bbb70c   3 years ago    84.9MB
```
>What's the advantage of termurin? Why not openjdk:17-alpine

I think support is being wound down for openjdk docker images:
https://github.com/docker-library/openjdk/issues/505

**Comment by johnmay** [comment]
good to bump for next release

**Pull request merged**
